version: '3.7'

services:
  frontend:
    image: karstendick/book-laurels-frontend:latest
    ports:
      - '80:80'

  # sample-prod:
  #   container_name: sample-prod
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-prod
  #   ports:
  #     - '80:80'
